#!/usr/bin/env bash
set -euo pipefail

# Future migration provisioner — provisions Azure infrastructure when migrating from Supabase.
# The current MVP uses Supabase ($0/month). Run this only when you are ready to migrate.
# See docs/plan/QUICKSTART_AZURE.md for the migration guide.
#
# Creates:
# - Resource Group
# - Storage Account + blob containers + queue
# - App Service Plan (F1) + Linux Web App
# - Optional Cosmos DB (serverless + free tier request)
# - Optional Azure Database for PostgreSQL Flexible Server (B1ms)

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

RESOURCE_GROUP="transcribedd-rg"
LOCATION="eastus"
PROJECT_PREFIX="transcribedd"
APP_RUNTIME="NODE|20-lts"
DATABASE_OPTION="none" # none|cosmos|postgres
SUBSCRIPTION_ID=""
SKIP_WEBAPP="false"
PG_ADMIN_USER="tddadmin"
PG_ADMIN_PASSWORD=""
PG_VERSION="16"

usage() {
  cat <<'EOF'
Usage: ./scripts/setup/setup-azure.sh [options]

Low-cost Azure provisioning for Transcribedd.

Options:
  --resource-group <name>    Azure resource group (default: transcribedd-rg)
  --location <region>        Azure region (default: eastus)
  --project-prefix <prefix>  Resource name prefix (default: transcribedd)
  --database <none|cosmos|postgres>
                             Optional database creation (default: none)
  --subscription <id>        Azure subscription ID (optional)
  --pg-admin-user <name>     PostgreSQL admin username (default: tddadmin)
  --pg-admin-password <pwd>  PostgreSQL admin password (default: autogenerated)
  --pg-version <version>     PostgreSQL major version (default: 16)
  --skip-webapp              Skip App Service plan/web app creation
  -h, --help                 Show this help

Examples:
  ./scripts/setup/setup-azure.sh
  ./scripts/setup/setup-azure.sh --database cosmos
  ./scripts/setup/setup-azure.sh --database postgres
  ./scripts/setup/setup-azure.sh --location australiaeast --project-prefix tdd
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --resource-group)
      RESOURCE_GROUP="$2"
      shift 2
      ;;
    --location)
      LOCATION="$2"
      shift 2
      ;;
    --project-prefix)
      PROJECT_PREFIX="$2"
      shift 2
      ;;
    --database)
      DATABASE_OPTION="$2"
      shift 2
      ;;
    --subscription)
      SUBSCRIPTION_ID="$2"
      shift 2
      ;;
    --pg-admin-user)
      PG_ADMIN_USER="$2"
      shift 2
      ;;
    --pg-admin-password)
      PG_ADMIN_PASSWORD="$2"
      shift 2
      ;;
    --pg-version)
      PG_VERSION="$2"
      shift 2
      ;;
    --skip-webapp)
      SKIP_WEBAPP="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      usage
      exit 1
      ;;
  esac
done

if [[ "$DATABASE_OPTION" != "none" && "$DATABASE_OPTION" != "cosmos" && "$DATABASE_OPTION" != "postgres" ]]; then
  echo -e "${RED}Invalid --database value: $DATABASE_OPTION (expected none|cosmos|postgres)${NC}"
  exit 1
fi

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo -e "${RED}Missing dependency: $cmd${NC}"
    exit 1
  fi
}

log() {
  echo -e "${BLUE}==>${NC} $1"
}

success() {
  echo -e "${GREEN}✓${NC} $1"
}

warn() {
  echo -e "${YELLOW}!${NC} $1"
}

sanitize_name() {
  tr '[:upper:]' '[:lower:]' <<<"$1" | tr -cd 'a-z0-9'
}

unique_suffix() {
  date +%m%d%H%M | tail -c 5
}

generate_password() {
  LC_ALL=C tr -dc 'A-Za-z0-9!@#%^*_=+' </dev/urandom | head -c 28
}

resource_exists() {
  local type="$1"
  local name="$2"
  az resource list --resource-group "$RESOURCE_GROUP" \
    --query "[?type=='${type}' && name=='${name}'] | length(@)" -o tsv 2>/dev/null | grep -q '^1$'
}

require_cmd az

log "Checking Azure login"
if ! az account show >/dev/null 2>&1; then
  warn "You are not logged in. Opening browser login..."
  az login >/dev/null
fi

if [[ -n "$SUBSCRIPTION_ID" ]]; then
  log "Setting subscription: $SUBSCRIPTION_ID"
  az account set --subscription "$SUBSCRIPTION_ID"
fi

ACTIVE_SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
ACTIVE_SUBSCRIPTION_NAME="$(az account show --query name -o tsv)"

success "Using subscription: ${ACTIVE_SUBSCRIPTION_NAME} (${ACTIVE_SUBSCRIPTION_ID})"

BASE_NAME="$(sanitize_name "$PROJECT_PREFIX")"
if [[ -z "$BASE_NAME" ]]; then
  echo -e "${RED}Project prefix produced an empty resource name. Use letters/numbers.${NC}"
  exit 1
fi

RANDOM_SUFFIX="$(unique_suffix)"
STORAGE_ACCOUNT_NAME="$(sanitize_name "${BASE_NAME}${RANDOM_SUFFIX}")"
STORAGE_ACCOUNT_NAME="${STORAGE_ACCOUNT_NAME:0:24}"

WEBAPP_NAME="$(sanitize_name "${BASE_NAME}-api-${RANDOM_SUFFIX}")"
WEBAPP_NAME="${WEBAPP_NAME:0:60}"
APP_PLAN_NAME="$(sanitize_name "${BASE_NAME}-plan-${RANDOM_SUFFIX}")"
APP_PLAN_NAME="${APP_PLAN_NAME:0:40}"

COSMOS_ACCOUNT_NAME="$(sanitize_name "${BASE_NAME}db${RANDOM_SUFFIX}")"
COSMOS_ACCOUNT_NAME="${COSMOS_ACCOUNT_NAME:0:44}"
COSMOS_DB_NAME="${BASE_NAME}"

POSTGRES_SERVER_NAME="$(sanitize_name "${BASE_NAME}pg${RANDOM_SUFFIX}")"
POSTGRES_SERVER_NAME="${POSTGRES_SERVER_NAME:0:63}"
POSTGRES_DB_NAME="${BASE_NAME}"

AUDIO_CONTAINER="audio-files"
TRANSCRIPT_CONTAINER="transcripts"
QUEUE_NAME="transcription-jobs"

log "Creating/updating resource group: $RESOURCE_GROUP ($LOCATION)"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" >/dev/null
success "Resource group ready"

log "Creating storage account: $STORAGE_ACCOUNT_NAME"
az storage account create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$STORAGE_ACCOUNT_NAME" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --allow-blob-public-access false \
  --min-tls-version TLS1_2 >/dev/null
success "Storage account ready"

STORAGE_CONNECTION_STRING="$(az storage account show-connection-string \
  --resource-group "$RESOURCE_GROUP" \
  --name "$STORAGE_ACCOUNT_NAME" \
  --query connectionString -o tsv)"

log "Creating blob containers and queue"
az storage container create --name "$AUDIO_CONTAINER" --connection-string "$STORAGE_CONNECTION_STRING" --auth-mode key >/dev/null
az storage container create --name "$TRANSCRIPT_CONTAINER" --connection-string "$STORAGE_CONNECTION_STRING" --auth-mode key >/dev/null
az storage queue create --name "$QUEUE_NAME" --connection-string "$STORAGE_CONNECTION_STRING" --auth-mode key >/dev/null
success "Storage containers and queue ready"

# Match retention decisions from docs/plan/DECISIONS.md:
# - audio files: 24h
# - transcripts: 180 days
log "Applying storage lifecycle policy (audio: 1 day, transcripts: 180 days)"
az storage account management-policy create \
  --account-name "$STORAGE_ACCOUNT_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --policy '{
    "rules": [
      {
        "enabled": true,
        "name": "delete-audio-after-1-day",
        "type": "Lifecycle",
        "definition": {
          "actions": {
            "baseBlob": {
              "delete": { "daysAfterModificationGreaterThan": 1 }
            }
          },
          "filters": {
            "blobTypes": ["blockBlob"],
            "prefixMatch": ["audio-files/"]
          }
        }
      },
      {
        "enabled": true,
        "name": "delete-transcripts-after-180-days",
        "type": "Lifecycle",
        "definition": {
          "actions": {
            "baseBlob": {
              "delete": { "daysAfterModificationGreaterThan": 180 }
            }
          },
          "filters": {
            "blobTypes": ["blockBlob"],
            "prefixMatch": ["transcripts/"]
          }
        }
      }
    ]
  }' >/dev/null
success "Storage lifecycle policy applied"

if [[ "$SKIP_WEBAPP" == "false" ]]; then
  log "Creating App Service plan (Free tier): $APP_PLAN_NAME"
  az appservice plan create \
    --name "$APP_PLAN_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku F1 \
    --is-linux >/dev/null

  log "Creating Web App: $WEBAPP_NAME"
  az webapp create \
    --name "$WEBAPP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --plan "$APP_PLAN_NAME" \
    --runtime "$APP_RUNTIME" >/dev/null

  az webapp config appsettings set \
    --name "$WEBAPP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --settings \
      NODE_ENV=production \
      AZURE_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING" \
      AZURE_QUEUE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING" \
      AUDIO_CONTAINER="$AUDIO_CONTAINER" \
      TRANSCRIPT_CONTAINER="$TRANSCRIPT_CONTAINER" \
      QUEUE_NAME="$QUEUE_NAME" >/dev/null

  success "Web App ready"
fi

COSMOS_ENDPOINT=""
COSMOS_KEY=""
POSTGRES_HOST=""
POSTGRES_ADMIN_PASSWORD="$PG_ADMIN_PASSWORD"
if [[ "$DATABASE_OPTION" == "cosmos" ]]; then
  log "Creating Cosmos DB account (serverless; free tier requested)"
  set +e
  az cosmosdb create \
    --name "$COSMOS_ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --locations regionName="$LOCATION" failoverPriority=0 isZoneRedundant=False \
    --enable-free-tier true \
    --capabilities EnableServerless >/dev/null 2>&1
  COSMOS_EXIT=$?
  set -e

  if [[ $COSMOS_EXIT -ne 0 ]]; then
    warn "Cosmos DB create with free-tier request failed (often due to existing free-tier account). Retrying without free-tier flag."
    az cosmosdb create \
      --name "$COSMOS_ACCOUNT_NAME" \
      --resource-group "$RESOURCE_GROUP" \
      --locations regionName="$LOCATION" failoverPriority=0 isZoneRedundant=False \
      --capabilities EnableServerless >/dev/null
  fi

  az cosmosdb sql database create \
    --account-name "$COSMOS_ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --name "$COSMOS_DB_NAME" >/dev/null

  COSMOS_ENDPOINT="$(az cosmosdb show --name "$COSMOS_ACCOUNT_NAME" --resource-group "$RESOURCE_GROUP" --query documentEndpoint -o tsv)"
  COSMOS_KEY="$(az cosmosdb keys list --name "$COSMOS_ACCOUNT_NAME" --resource-group "$RESOURCE_GROUP" --type keys --query primaryMasterKey -o tsv)"
  success "Cosmos DB ready"
fi

if [[ "$DATABASE_OPTION" == "postgres" ]]; then
  if [[ -z "$POSTGRES_ADMIN_PASSWORD" ]]; then
    POSTGRES_ADMIN_PASSWORD="$(generate_password)"
  fi

  log "Creating PostgreSQL Flexible Server (Burstable B1ms): $POSTGRES_SERVER_NAME"
  az postgres flexible-server create \
    --resource-group "$RESOURCE_GROUP" \
    --name "$POSTGRES_SERVER_NAME" \
    --location "$LOCATION" \
    --admin-user "$PG_ADMIN_USER" \
    --admin-password "$POSTGRES_ADMIN_PASSWORD" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --version "$PG_VERSION" \
    --storage-size 32 \
    --public-access 0.0.0.0 \
    --database-name "$POSTGRES_DB_NAME" \
    --yes >/dev/null

  POSTGRES_HOST="$(az postgres flexible-server show --resource-group "$RESOURCE_GROUP" --name "$POSTGRES_SERVER_NAME" --query fullyQualifiedDomainName -o tsv)"
  success "PostgreSQL ready"
fi

OUTPUT_FILE="${ROOT_DIR}/scripts/setup/.azure-output.env"
cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/setup/setup-azure.sh
AZURE_SUBSCRIPTION_ID=${ACTIVE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${RESOURCE_GROUP}
AZURE_LOCATION=${LOCATION}
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
AUDIO_CONTAINER=${AUDIO_CONTAINER}
TRANSCRIPT_CONTAINER=${TRANSCRIPT_CONTAINER}
QUEUE_NAME=${QUEUE_NAME}
AZURE_QUEUE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
WEBAPP_NAME=${WEBAPP_NAME}
APP_SERVICE_PLAN=${APP_PLAN_NAME}
WEBAPP_URL=https://${WEBAPP_NAME}.azurewebsites.net
COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
COSMOS_KEY=${COSMOS_KEY}
COSMOS_DATABASE=${COSMOS_DB_NAME}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=5432
POSTGRES_DATABASE=${POSTGRES_DB_NAME}
POSTGRES_ADMIN_USER=${PG_ADMIN_USER}
POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
DATABASE_URL=postgresql://${PG_ADMIN_USER}:${POSTGRES_ADMIN_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB_NAME}?sslmode=require
EOF

success "Saved outputs to ${OUTPUT_FILE}"

echo
echo "Low-cost Azure setup complete."
echo "Resource Group: ${RESOURCE_GROUP}"
echo "Storage Account: ${STORAGE_ACCOUNT_NAME}"
if [[ "$SKIP_WEBAPP" == "false" ]]; then
  echo "Web App: ${WEBAPP_NAME}"
  echo "Web App URL: https://${WEBAPP_NAME}.azurewebsites.net"
fi
if [[ "$DATABASE_OPTION" == "cosmos" ]]; then
  echo "Cosmos DB Account: ${COSMOS_ACCOUNT_NAME}"
fi
if [[ "$DATABASE_OPTION" == "postgres" ]]; then
  echo "PostgreSQL Server: ${POSTGRES_SERVER_NAME}"
  echo "PostgreSQL Host: ${POSTGRES_HOST}"
fi
echo
echo "Next steps:"
echo "1. Review scripts/setup/.azure-output.env"
echo "2. Copy values into your backend .env"
echo "3. Deploy backend app code to the web app"
